### ISSUE TITLE
Lab 2 question

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-529-spr-2023#1]
Hi @AntJam-Howell! I have a question on lab 2, question 2b. I am creating a difference score for the `HHInc_HousePrice_Ratio` variable for each 5-year period. To do this, I had to coerce the `CenDF` object to a dataframe like this:

```

# create the separate objects we want to join
df.17 <- as.data.frame( CenDF )  %>% # had to coerce here
  select( GEOID, HHInc_HousePrice_Ratio ) %>% 
  rename( HHInc_HousePrice_Ratio.17 = "HHInc_HousePrice_Ratio" )

df.12 <- as.data.frame( CenDF.12 ) %>%  # had to coerce here
  select( GEOID, HHInc_HousePrice_Ratio ) %>% 
  rename( HHInc_HousePrice_Ratio.12 = "HHInc_HousePrice_Ratio" )

# join them
both.year <- full_join( 
  df.17, df.12, 
  by = join_by( GEOID ) )

# create the difference score
both.year$HHInc_HousePrice_Ratio.d <- 
  both.year$HHInc_HousePrice_Ratio.17 - both.year$HHInc_HousePrice_Ratio.12 

``` 

The coercion is in the `as.data.frame()` commands. I had to do this because I was getting an error saying: "Error: y should not have class sf; for spatial joins, use st_join"

Is there a better way to do this? That is, to join these classes of objects? I saw the `st_join` function. But, since it was not in the lecture I wasn't sure about using it.

Let me know. Thanks!

**Comment by AntJam-Howell** [comment]
Hi @jacobtnyoung, 
welcome to the class and good question.  For the purposes of this lab, makes sense to convert the `sf` dataframes as you did.  If further spatial analysis were to be conducted though, you would have to convert them back to `sf`.  In that case, would be better to bring in the `sf` library and use the `st_join`.  

Best,

**Comment by jacobtnyoung** [comment]
Cool. Thanks @AntJam-Howell.
