### ISSUE TITLE
Final project question

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-529-spr-2023#10]
Hi @AntJam-Howell! In the instructions for the final project, it says to use a city of our choice. But, in lab 4 it says we are supposed to use San Diego for the final project (as we did for lab 4).

Could you clarify this? Can we use a city of our choice? Or does it need to be San Diego?

Thanks!

**Comment by AntJam-Howell** [comment]
@jacobtnyoung Thanks for pointing this out.  Best to use San Diego given earlier completed work from Lab 4.  

Could you point me to where you are reading select your own city in the final project instructions?  I couldn't find that language in the final project (dashboard) instructions on the course schedule page [https://watts-college.github.io/cpp-529-spr-2023/schedule/]((Link)).  I'll go back and change the wording to be consistent with lab 4 language.

**Comment by jacobtnyoung** [comment]
Hi @AntJam-Howell! Oh ok thanks.

I think it is just the "your city" language that was confusing me. 

Thanks for the help!

**Comment by AntJam-Howell** [comment]
@jacobtnyoung no worries. Thanks for the note.  Just updated the wording to San Diego to avoid any confusion for others as well.  Thanks!
