### ISSUE TITLE
dashboard question

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-529-spr-2023#12]
Hi @AntJam-Howell ! I am running into a problem getting the correlation plot to work on my dashboard. I emailed you the .Rmd file. Just wanted to see if you would prefer I post the question here. Thanks!

**Comment by AntJam-Howell** [comment]
@jacobtnyoung On the right track.  Looks like just need to use `renderPlot` for coefficient plot  instead of renderUI, which is used in the previous chunk to create table results of the linear model. 
Let me know if that fixes the issue. 

Best,

**Comment by jacobtnyoung** [comment]
Hi @AntJam-Howell! I had that in there and it was still giving an error. I will take another crack at it. But, if you have some additional thoughts, please past them along. Will keep you posted!

**Comment by AntJam-Howell** [comment]
@jacobtnyoung Ok, give it a try.  The exact code I have after changing to `renderPlot` is below, and was able to get it to run and show the correlation plot on the dashboard.  Let me know if have any issues though.   




`get_home <- reactive({ input$dv })

renderPlot({

  covariates <- get_covariates()
  
  df <- data.frame(covariates)
  
  pairs( d[covariates], col = c("blue", "dark green"))

})`

**Comment by jacobtnyoung** [comment]
Thanks @jacobtnyoung. I will tinker with it.

**Comment by jacobtnyoung** [comment]
I feel dumb now. I got it to work:

```
get_covariates2 <-  reactive({ c( input$dv, input$covariates ) }) # needed to add the other input here!!!

renderPlot({

  covariates2 <- get_covariates2()  
  pairs( d[covariates2], col = "darkgreen" )

})

```

Thanks @AntJam-Howell for your help!
