### ISSUE TITLE
Issue publishing final project

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-529-spr-2023#14]
Hi @AntJam-Howell! I am trying to publish my final project to shiny. I keep getting this error:

![Screen Shot 2023-04-13 at 10 22 47 AM](https://user-images.githubusercontent.com/39632608/231837129-1587ea0b-e78a-4104-9268-8548c7ffaa77.png)

It is uploading the project to my shiny account. But, it is showing as "undeployed". Based on the error message, it seems to be some error with the package `sf`. Any ideas?

**Comment by jacobtnyoung** [comment]
Hi @AntJam-Howell. I figured it out. Here was the problem:

When you load the .Rmd file prior to opening RStudio, it loads the package `sf`. Not sure why it does this. 

But, if you open RStudio, _then_ open the .Rmd file it does not load 'sf'. 

I also downloaded the most recent versions of R, RStudio, and reinstalled all the packages. But, I think the issue was opening the .Rmd file prior to opening RStudio.

**Comment by AntJam-Howell** [comment]
@jacobtnyoung That is strange.  After I updated my sf package, had serious troubles with it updating dependencies and had to use terminal to and use brew install gdal to get sf and dependencies working correctly.  Not sure whats going on. Glad you got it figured out.

**Comment by CarlyDeal** [comment]
@AntJam-Howell  I am currently getting the same error, but nothing is showing up In my shiny account.

**Comment by CarlyDeal** [comment]
I was able to get it to work, I quit out of R and started again and it finally worked. Not exactly sure what was going on, but all good now!
