### ISSUE TITLE
Lab 02 - Map

### ISSUE THREAD

**Issue by mbrentli** [Watts-College/cpp-529-spr-2023#22]
I'm having trouble figuring out how to rescale the map/plot so that there isn't so much empty space and it more properly fills the plot without stretching or squishing one way or the other.

Here's what the output looks like:

<img width="535" alt="image" src="https://github.com/Watts-College/cpp-529-spr-2023/assets/121507825/ba1b3e89-1171-4f8b-acad-aa83fde09543">

Here are some of the things I have tried (many suggestions from google/chatgpt) but it doesn't seem to be working, either:

```

# # Ensure proper CRS is set
# CenDFwide <- st_set_crs(CenDFwide, 4326) # Assuming WGS84 CRS
# 
# # Calculate the range of x and y coordinates
# x_range <- range(st_coordinates(CenDFwide)[, "X"], na.rm = TRUE)
# y_range <- range(st_coordinates(CenDFwide)[, "Y"], na.rm = TRUE)
# 
# # Check for finite values in the coordinate ranges
# if (!all(is.finite(c(x_range, y_range)))) {
#   stop("Non-finite coordinate range detected.")
# }
# 
# 
# # Calculate aspect ratio
# aspect_ratio <- diff(y_range) / diff(x_range)
# 
# ## Plot
# ggplot(CenDFwide) +
#   geom_sf(aes(fill = HHInc_HousePrice_Ratio), color=NA) +
#   coord_sf(datum=NA, 
#            xlim = c(min(CenDFwide$geometry$X), max(CenDFwide$geometry$X)) , # Set xlim
#             lims_method = "geometry_bbox") + # Set lims_method explicitly
#   labs(title = "House-Price-to-Income Ratio by US County",
#        subtitle = "Alaska and Hawaii are shifted and not to scale",
#        caption = "Source: ACS 5-year, 2017",
#        fill = "Price to Income Ratio") +
#   scale_fill_viridis(direction=-1) +
#   theme(aspect.ratio = aspect_ratio)
```

Any ideas here, or are we destined to the tiny map and a bunch of blank space (and CenDFwide is what I called the data after transforming to wide, so that i could have a long and wide version in case i wanted to look back...but it should be the same as CenDF if you've been overwriting for every process)?

**Comment by AntJam-Howell** [comment]
@mbrentli Can you attach or send me your RMD file.  The map dimensions can be augmented. I will take a look at your code to spot the problem. 
best

**Comment by mbrentli** [comment]
@AntJam-Howell I have tried several things to try to change dimensions and aspect, but none of them are reducing the blankspace without stretching or squishing the actual map itself.  I'll send you the rmd shortly.  Thank you!

**Comment by mbrentli** [comment]
Per the suggestion in the other issue, I tried adding  shift_geo=TRUE to the get_acs() function and it is showing properly now
