### ISSUE TITLE
Final project - Github Raw URL for Geojson file

### ISSUE THREAD

**Issue by swest235** [Watts-College/cpp-529-spr-2023#28]
Has anyone else had issues getting the github raw url for your geojson file? I've uploaded my geojson file to my repositiory but my permanent link produces a 404 error when I run it in R. 

Everything I've looked up explains there should be a 'raw' button when I open my file in github but there isn't, just a permanent path, copy path, and download raw file - which the only link produced is permanent path, but again I get a 404 error with this link. 

To clarify, when I hit the download raw file button it just downloads the geojson file to my local drive, no link to use in R. 

@AntJam-Howell

**Comment by swest235** [comment]
@AntJam-Howell I just tried it and that worked, thank you! 

Are you familiar with why the "raw" button github says should be there isn't there? Or is that dorling specific? I saw another thread from a previous semester that said to just download it and a link will show - but I just get the original file locally when i do that. 

Any clue what I'm doing wrong?

![image](https://github.com/Watts-College/cpp-529-spr-2023/assets/146388467/16b6b8b2-cfd1-467e-8992-b8689fdff8f3)

**Comment by ashleycc33** [comment]
Hi there, 
I am still running into the HTTP 404 issue, even after updating

**Comment by swest235** [comment]
> Hi there, I am still running into the HTTP 404 issue, even after updating the link mentioned above.

@ashleycc33 did you copy/paste the link or edit your link to look like his? In case there was any confusion, you have to upload your geojson file to your github account, then go to your repository, select the file and open it. When opened, copy and paste the link to your R markdown file but edit it to be along the lines of what Howell mentioned. It worked for me with a little tinkering.

**Comment by ashleycc33** [comment]
Hi @swest235  yes, I've uploaded it, edited what Prof. Howell mentioned - still getting 404 error :( Do you mind if I share some code?
