### ISSUE TITLE
Lab 2: Step 2 Transforming Dataset from Long to Wide

### ISSUE THREAD

**Issue by CarlyDeal** [Watts-College/cpp-529-spr-2023#3]
I am working on Step 2, transforming the dataset from long to wide using spread() but getting an error due to keys being shared for multiple rows. This is because for each county it lists the same county twice with a different value for household income and median household price. My code seems to be the same from the slides, so not sure if something needs to be changed on my end? R Forums are suggesting to use pivot_longer() instead of spread. Would that be a better choice instead of spread, considering this issue?

```{r}

library(tidyr)
NewCenDF<-CenDF %>% 
  mutate(variable=case_when(
    variable=="B25077_001" ~ "MedianHHV",
    variable=="B19326_001" ~ "MedianHHInc")) %>%
  select(-moe)  %>%
  spread(variable, estimate) %>%  #Spread moves rows into columns
  mutate(HHInc_HousePrice_Ratio=round(MedianHHV/MedianHHInc,2)) 
```

Error that I receive:

Error in tidyr::spread(data, !!key, !!value, fill = fill, convert = convert, :

ℹ Keys are shared for 6440 rows
• 1, 2
• 3, 4
• 5, 6
• 7, 8
• 9, 10
• 11, 12
• 13, 14
• 15, 16
• 17, 18
• 19, 20
• 21, 22
• 23, 24

etc.

**Comment by jacobtnyoung** [comment]
Hi @CarlyDeal! I ran into this problem also. I had to remove these lines:

```

mutate(variable=case_when(
    variable=="B25077_001" ~ "MedianHHV",
    variable=="B19326_001" ~ "MedianHHInc"))

```

So, I used this:

```

vars.to.use <- c( HHIncome = "B19049_001",
                  HouseValue = "B25077_001" )

CenDF <- get_acs( geography="county", 
                  year=2017, 
                  survey="acs5",
                  variables=vars.to.use,
                  geometry=TRUE,
                  shift_geo=TRUE )

CenDF<-CenDF %>% 
  select( -moe ) %>%  
  spread( variable, estimate ) %>%
  mutate( HHInc_HousePrice_Ratio = ( HouseValue/HHIncome ) )

```

**Comment by CarlyDeal** [comment]
@jacobtnyoung  Thank you!! That worked for me!

**Comment by AntJam-Howell** [comment]
Hi @CarlyDeal, @jacobtnyoung  is correct!  And apologies, I'm just now seeing this comment. Please make sure to add my @AntJam-Howell handle in order for me to receive the notice. 

Best,
