### ISSUE TITLE
Missing object definition for Creating Color Scales for Choropleth Maps page

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-529-spr-2023#6]
Hi @AntJam-Howell! On the Creating Color Scales for Choropleth Maps page, there is an object called `cut.points` that is not defined in the code. Or, if it there, I missed it. Could you add that? Thanks!

**Comment by AntJam-Howell** [comment]
Hi @jacobtnyoung Let me take a look.  Is it part of the lab or the course website?  Could you paste the link of the page or let me know which lab? 

Best,

**Comment by jacobtnyoung** [comment]
@AntJam-Howell On the week 5 tutorials on the course website. The third tutorial. About adding color. I am away from my computer right now, but I can find the page later.

**Comment by AntJam-Howell** [comment]
Hi @jacobtnyoung  I found it.   It looks like the `cut.points` is assigned a bit later on in the tutorial causing the code to fail.  I placed the assignment `cut.points <- quantile( x, seq(0,1,0.1) )` near the top of the tutorial, so the code should work now.

**Comment by jacobtnyoung** [comment]
https://watts-college.github.io/cpp-529-spr-2023/choropleth-color-scales/

**Comment by jacobtnyoung** [comment]
Great! Thanks @AntJam-Howell
